# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7002d22e54eeb0e55f8b9b4751d33f08a0c9df0684d80c252e3aa28d3f31917b7708fbc34fb09297df8c0a8366bace032809786f8371d285f1ec3c4c0d8f1dbc

test:
  secret_key_base: 1af66acd90d5ebcd48a2fe43d89f9d68f901ee7afe8ff3cc534990b795befbde70923854a23a16482ca1104f6bf94d54cc930f782861f355526db27eec2758e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
